### ISSUE TITLE
BUG: Unable to correctly read the 32 bit IBM Floating point numbers from trace headers

### ISSUE THREAD

**Issue by amitpendharkar** [TGSAI/segy#168]
### **Details:**
Segy version 0.1.5 is unable to correctly read the values stored in trace headers in 32 bit IBM Floating point format.
It does not give any error while doing so.

### **Expected output**
The values at locations 197 (32 bit IBM Float) and 233 (32 bit IBM Float) both are 15.0

### **How to reproduce**
1. Download the attached single trace zip file and unzip it to create a sgy file
[Single_Trace_197ibmf_233ibmf_15.zip](https://github.com/user-attachments/files/16490796/Single_Trace_197ibmf_233ibmf_15.zip)
2. Run following code to see that the value printed is indeed wrong (and not 15.0)
```python
from segy import SegyFile  
from segy.schema import HeaderField
from segy.standards import get_segy_standard

uri_path = "Single_Trace_197ibmf_233ibmf_15.sgy"
rev1 = get_segy_standard(1.0)
custom_spec = rev1.customize(                                   # Binary header info not needed
    trace_header_fields=[
        HeaderField(name="AZ", byte=197, format="ibm32"),       # Trace header to read value from
        HeaderField(name="AZ_COPY", byte=233, format="ibm32"),  # Trace header to read value from
    ],
)
sgy = SegyFile(uri_path, spec=custom_spec)

traces = sgy.trace[0:1] # Get first trace

print(traces.header) # This prints (1106247680, 1106247680) and not (15, 15)
```

**Comment by tasansal** [comment]
Interesting! 

`sgy.header[0]` reads it fine, must be a problem with the transform pipeline. Will take a look.
