### ISSUE TITLE
Write custom exceptions

### ISSUE THREAD

**Issue by tasansal** [TGSAI/segy#35]
For common exceptions, we should make nice error messages for users.

**Comment by kachida** [comment]
Hi @tasansal , I'm interested in looking on to this issue, can you please assign me this task

**Comment by tasansal** [comment]
Hi @kachida 👋🏻 

Thanks for your interest. Of course, I'll assign it to you. Can you elaborate on your planned code changes?

**Comment by tasansal** [comment]
@kachida just wanted to check if you're still interested in doing this.

**Comment by tasansal** [comment]
this is ongoing and we add as we go, going to close
